### ISSUE TITLE
Where is dataset

### ISSUE THREAD

**Issue by jianlong-yuan** [Kai-46/SatelliteNeRF#1]

**Comment by jianlong-yuan** [comment]
Where is "/share/phoenix/nfs04/S7/kz298/satellite_stuff/dfc2019_data_clean/JAX_165", could we download it?

**Comment by Kai-46** [comment]
Those data were the outputs of the [SatelliteSfM package](https://github.com/Kai-46/SatelliteSfM). You can download the raw data from the data source linked in that repo's readme file, and run SatelliteSfM package to process the raw data.

**Comment by jianlong-yuan** [comment]
![image](https://user-images.githubusercontent.com/18137551/155083794-9d5f6aad-733b-44e8-83a9-2732e00dca86.png)

This is different. where is     "cam_dict = json.load(open(os.path.join(basedir, split, 'cam_dict_norm.json')))"

**Comment by Kai-46** [comment]
Please run SatelliteSfM on this data according to that repo's readme. In fact, that repo's readme has a lot of information, and is worth checking carefully, I guess.
