### ISSUE TITLE
Could you provide your training data ?

### ISSUE THREAD

**Issue by jianlong-yuan** [Kai-46/SatelliteNeRF#2]
I try my best to compile SatelliteSFM，but I got a series problem . Could you provide your processed data? Thank you

**Comment by Kai-46** [comment]
I just released the preprocessed satellite data here: [google drive](https://drive.google.com/drive/folders/1Do7oF36sCEBWrcIiCzgHbhF5kQMawjVo). I encourage you to check the SatelliteSfM readme  how to normalize the cameras so that the scene is inside a bounding box.
